# 训练配置文件

# 数据集配置
dataset:
  train_root: "work/train_samples"
  val_root: "work/val_samples"
  image_size: [640, 640]
  batch_size: 8
  num_workers: 2
  shuffle: true

# 模型配置
model:
  backbone: "unet"
  input_size: [640, 640]
  init_features: 32
  out_channels: 4

# 训练配置
train:
  epochs: 100
  learning_rate: 0.001
  weight_decay: 0.0001
  save_dir: "work"
  save_interval: 10
  log_interval: 100

# 优化器配置
optimizer:
  type: "Adam"
  beta1: 0.9
  beta2: 0.999

# 损失函数配置
loss:
  type: "MSELoss"
  reduction: "mean"

# 评估配置
eval:
  iou_threshold: 0.85
  nme_threshold: 0.03
  eval_interval: 10

# 数据增强配置
data_augmentation:
  enable: true
  brightness: 0.2
  contrast: 0.2
  saturation: 0.2
  hue: 0.1
  rotation: 10
  flip: true
